# Autogenerated wrapper script for OpenGLMathematics_jll for any
export glm_hpp

JLLWrappers.@generate_wrapper_header("OpenGLMathematics")
JLLWrappers.@declare_file_product(glm_hpp)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        glm_hpp,
        "include/glm/glm.hpp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
